### ISSUE TITLE
Tasks locations

### ISSUE THREAD

**Issue by behdanisohrab** [shahriaarrr/Tasky#1]
set a location for storing tasks instead of making .tasky.json in the current directory.

for example .tasky/tasks.json in home directory.

![issue image](https://imgurl.ir/uploads/u89357_Screenshot_20230925_142300.png)

**Comment by shahriaarrr** [comment]
Hi @behdanisohrab 
Thank you for reporting this bug 🙏
Please delete line 14 in the `main.go` file and replace it with this, test it and take a screenshot of the result.
```go
const taskFile = ".taskyDB/tasks.json"
```

**Comment by behdanisohrab** [comment]
after adding the code this was the output.
it should create the folder in its first launch if not exists.
```
➜ ./tasky -add test
open .taskyDB/tasks.json: no such file or directory

```

**Comment by behdanisohrab** [comment]
so i added the function for making folder to your code, but it can`t make tasks.json there.

```go
func createTaskDBFolder() error {
    // Get the current user's home directory
    currentUser, err := user.Current()
    if err != nil {
        return err
    }

    // Define the path to the .taskDB folder in the home directory
    taskDBFolderPath := filepath.Join(currentUser.HomeDir, ".taskDB")

    // Check if the folder already exists
    _, err = os.Stat(taskDBFolderPath)
    if os.IsNotExist(err) {
        // Folder does not exist, so create it
        err := os.MkdirAll(taskDBFolderPath, 0755)
        if err != nil {
            return err
        }
        fmt.Println("Created .taskDB folder in the home directory.")
    } else if err != nil {
        // An error occurred while checking the folder's existence
        return err
    }

    return nil
}
```

and this to main function
```go
createTaskDBFolder()

```


i think it cannot find the home directory itself.

**Comment by shahriaarrr** [comment]
I checked your code but it didn't work. I searched instead and found this method that answered for me.
Like last time, change line 14 and after line 22 ((where flags parse)) add this condition and test:
```go
if err := os.MkdirAll(filepath.Dir(taskFile), 0755); err != nil {
		fmt.Fprintln(os.Stderr, "Error creating .taskydb directory:", err.Error())
		os.Exit(1)
}
```

**Comment by shabane** [comment]
سلام.

شهریار بنظرم اینکه تسک ها توی دایرکتوریی که اجرا می‌شن درست می‌شه خیلی هم خوبه
ببین فرض کن یه ریپازیتوری رو کلون کردی
خب میای و tasky رو ران می‌کنی و تسک های همون ریپو رو می‌بینی
این خیلی خوبه، هر پروژه‌ای تسک های خودشو داره

فقط اینکه بجای ساخت یک فایل،
مثل گیت عمل کن و یه دایرکتوری بساز به اسم .tasky
و فایل های مربوطه رو اونجا بذار

حالا یه چیز دیگه


ببین اینکه خب نیازه تا تسک ها گلوبال تعریف بشن هم منطقیه
خب پس بجای اینکه تسک ها رو از دایرکتوری که داخلش اجرا شده بخونه باید از یه جای دیگه بخونه
خب خیلی ساده بیا و یه فلگ تعریف کن، مثلا global--
این میاد چیکار می‌کنه؟

بجای اینکه تسک ها رو توی دایکتوری که اجرا شده بریزه، میاد و تسک ها رو توی home کاربر می‌سازه
و دقت کن باید توی یه دایرکتوری باشه اون داده هاش.

پس اینطوری هر دو روش رو داری ساپورت می‌کنی

یه چیز باحال تر هم بگم که اگه پیاده کنی خدا میشه اپ‌ت


ببین فرض کن تسک های داخل یک ریپو رو می‌خای به تسک های گلوبال اضافه کنی، و مدیریت‌ تمامی تسک های روزت برات راحت تر بشه

برای همین باید خروجی های مختلف روی تسک ها داشته باشی که مثلا بشه با یه پایپ خرجی رو داد به ورودی گلوبال

یه چیزی توی این مایه ها البته این بدی اینو داره که تسک ها اضافه می‌شه ولی بقیه دیتیل ها(تاریخ ها، اولویت ها) نه
tasky list —consice | tasky add —global


برای همین سوییچ‌ش رو خودت اضافه کن

tasky add —global —curent



کلا فلگ --curent به دایرکتوی فعلی اشاره می‌کنه ولی خب به این دقت کن که دیفالت همین سوییچ اجرا می‌شه و نیاز نیست کسی بزنه :)

**Comment by shabane** [comment]
لیبل باگ رو بردار، این فیچره :smile:

**Comment by shabane** [comment]
ببین برای اینکه home کاربر رو بگیری می‌تونی از env بگیری، انگار go یه فانکشن برای اینکار ساخته حتی!
همون رو استفاده کنی اوکی می‌شه. من کد رو تغییر دادم، البته تغییر درستی نیست و می‌تونی با یه فانکشن دیگه بهترش کنی، البته اکه ماژول path توی go هست که دیگه خیلی بهتر می‌شه چون دیگه توی os های مختلف به ارور نمی‌خوری(مخوصا سر `/\`)

[کد رو pastebin کردم](https://dpaste.org/73fmr)

بهتره diff بگیری 

![image](https://github.com/shahriaarrr/Tasky/assets/51704066/1c867abb-bfc4-44f7-999d-b7a10ff9ded6)

**Comment by shahriaarrr** [comment]
سلام @shabane ممنون ازت.با کدی که دادی مشکلش حل شده و طبق عکسی هم که دادی همه چیش اوکیه

**Comment by shahriaarrr** [comment]
> لیبل باگ رو بردار، این فیچره 😄

این یجورایی باگ بود چون با عوض شدن دایرکتوری و پارتیشن ها عملا امکان دسترسی به دیتا تسک ها نبود

**Comment by shahriaarrr** [comment]
it's done👌
thanks @shabane @behdanisohrab
