### ISSUE TITLE
git like log

### ISSUE THREAD

**Issue by shabane** [shahriaarrr/Tasky#2]
عام بنظرم یه لاگ بنویس شبیه لاگی که گیت خروجی می‌ده
اینطوری خیلی راحت می‌شه بین تسک ها، کامنت ها، تاریخ ها و کسایی که تسک رو تمومش کردن سرچ کرد،
این خروجی می‌تونه به less داده بشه برای اینکار.

**Comment by shahriaarrr** [comment]
سلام.
ایده ها رو توی بخش دیسکاشن چنل ایده ها مطرح کن
