### ISSUE TITLE
get user data

### ISSUE THREAD

**Issue by shabane** [shahriaarrr/Tasky#3]
یه چیزی که خیلی نیازه اینه که خب یه تسک رو کی انجام داده
بیا و یه گزینه درست کن که هروقت یه یوزر تسک رو تموم کرد
دیتای اون یوزر رو هم بنویسه بعنوان کسی که تسک رو تموم کرده.

**Comment by shahriaarrr** [comment]
سلام.
ایده ها رو توی بخش دیسکاشن چنل ایده ها مطرح کن
