### ISSUE TITLE
show the progresses

### ISSUE THREAD

**Issue by shabane** [shahriaarrr/Tasky#4]
یه فیچر دیگه که واقعا می‌تونه کمک کنه اینه که progress bar تحت ترمینال نشون بدی
دو نوع پروگرس نیازه 
- یکی برای اینکه چه تعداد تسک انجام شده بین کل تسک ها باقی مونده `[########__________]`
- دوم اینکه چقدر مونده برای رسیدن به اولین ددلاین، این می‌توی به صورت یه زمانی باشه البته 
```bash
[_____#####]
20 Minute left of 22 Hour
```

جریانش این هست که باید تسک ها رو زمان هاشون رو محاسبه کنه، مثلا اگه یه تسک از تاریخ فلان تا تاریخ فیلان وقت داشته، این محاسبه می‌کنه و میگه از 12 ساعت مثلا دیگه 2 ساعت مونده

همین فیچر رو با فلگ --all بده که همه تسک ها رو برات تایم هاشون رو حساب کنه.

**Comment by shahriaarrr** [comment]
سلام.
ایده ها رو توی بخش دیسکاشن چنل ایده ها مطرح کن
