### ISSUE TITLE
grouping tasks

### ISSUE THREAD

**Issue by shabane** [shahriaarrr/Tasky#5]
ببین بیشنر باید حالت اینرو داشته باشه که کابر بیاد و گروه های مختلف تعریف کنه
مثلا فرض کن بیاد و done, review, backlog, in progress اینا رو تعریف کنه و تسک های جدید که تعریف شدن خودکار برن توی گروهی که کاربر دیفالت‌ش کرده

البته این باید اختیاری باشه که تسک ها گروه داشته باشن

یه خوبی این ایده اینکه که کاربر می‌تونه برای بخش های مختلف یک پروژه گروه های مخلف تعریف کنه
و خب اینطوری می‌شه مثلا گروه های اینطوری ساخت front-end, back-end, 

و حالا یه تسک می‌تونه توی گروه فرانت باشه و هم توی گروه backlog مثلا

**Comment by shahriaarrr** [comment]
سلام.
ایده ها رو توی بخش دیسکاشن چنل ایده ها مطرح کن
