### ISSUE TITLE
wrong explain in help

### ISSUE THREAD

**Issue by shabane** [shahriaarrr/Tasky#6]
![image](https://github.com/shahriaarrr/Tasky/assets/51704066/2207af1a-f770-4621-bb60-f553e0f8faab)

 ببین برای یک کاربر نباید بگیم int، درسته منظورت از int عدد صحیح هست ولی خب منطقی نیست اینو بگیم
 باید مثلا task number باشه، خیلی ساده number یا حتی اگه id داره تسک ها که دیگه چه بهتر، ID می‌تونی بنویسی

**Comment by shahriaarrr** [comment]
سلام.
ایده ها رو توی بخش دیسکاشن چنل ایده ها مطرح کن
